# Generated by Django 6.0.6 on 2026-08-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_booking_check_out_after_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_at_booking',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
