# Generated by Django 6.0.6 on 2026-08-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotel_owner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_night__gt', 0)), name='price_per_night_positive'),
        ),
    ]
