# Generated by Django 6.0.6 on 2026-08-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_room_price_per_night_positive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-check_in']},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['id']},
        ),
    ]
